apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: my-thesis
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
